export const data = JSON.parse("{\"key\":\"v-184f4da6\",\"path\":\"/intro.html\",\"title\":\"Intro Page\",\"lang\":\"en-US\",\"frontmatter\":{\"icon\":\"info\",\"description\":\"Intro Page 🙋🏻‍♂️ About Me My name is Xiao Hai, born in the 1990s, graduated from the Haibin College of Beijing Jiaotong University with a bachelor's degree Now working in the State Key Laboratory of a university, doing code farmers Opened an online store during college, worked as a campus ambassador and forum moderator Also a self-media blogger, Vlogger An ARTS game is being developed, and I hope it will become popular. https://space.bilibili.com/331466888?spm_id_from=333.999.0.0\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/aps-xiao/apingstudio/intro.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"APingStudio\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Intro Page\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Intro Page 🙋🏻‍♂️ About Me My name is Xiao Hai, born in the 1990s, graduated from the Haibin College of Beijing Jiaotong University with a bachelor's degree Now working in the State Key Laboratory of a university, doing code farmers Opened an online store during college, worked as a campus ambassador and forum moderator Also a self-media blogger, Vlogger An ARTS game is being developed, and I hope it will become popular. https://space.bilibili.com/331466888?spm_id_from=333.999.0.0\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Intro Page\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://github.com/aps-xiao/apingstudio/zh/intro.html\"}]]},\"headers\":[],\"readingTime\":{\"minutes\":0.46,\"words\":139},\"filePathRelative\":\"intro.md\",\"excerpt\":\"<h1> Intro Page</h1>\\n<p>🙋🏻‍♂️ About Me\\nMy name is Xiao Hai, born in the 1990s, graduated from the Haibin College of Beijing Jiaotong University with a bachelor's degree<br>\\nNow working in the State Key Laboratory of a university, doing code farmers<br>\\nOpened an online store during college, worked as a campus ambassador and forum moderator<br>\\nAlso a self-media blogger, Vlogger<br>\\nAn ARTS game is being developed, and I hope it will become popular.<br>\\n<a href=\\\"https://space.bilibili.com/331466888?spm_id_from=333.999.0.0\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://space.bilibili.com/331466888?spm_id_from=333.999.0.0</a></p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
