export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"d":"2023-02-05T06:40:24.000Z","e":"<h1> Intro Page</h1>\n<p>🙋🏻‍♂️ About Me\nMy name is Xiao Hai, born in the 1990s, graduated from the Haibin College of Beijing Jiaotong University with a bachelor's degree<br>\nNow working in the State Key Laboratory of a university, doing code farmers<br>\nOpened an online store during college, worked as a campus ambassador and forum moderator<br>\nAlso a self-media blogger, Vlogger<br>\nAn ARTS game is being developed, and I hope it will become popular.<br>\n<a href=\"https://space.bilibili.com/331466888?spm_id_from=333.999.0.0\" target=\"_blank\" rel=\"noopener noreferrer\">https://space.bilibili.com/331466888?spm_id_from=333.999.0.0</a></p>","r":{"minutes":0.46,"words":139},"y":"a","t":"Intro Page","i":"info","I":1},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"Blog Home","i":"home","I":1},["/index.html","/README.md"]],
  ["v-858cfdd6","/zh/intro.html",{"d":"2023-02-05T06:40:24.000Z","e":"<h1> 介绍页</h1>\n<h2> 🙋🏻‍♂️ 关于我</h2>\n<p>我叫肖海，90后，本科毕业于北京交通大学海滨学院 <br>\n现工作于某高校的国家重点实验室，做码农 <br>\n曾在大学期间开过网店，做过校园大使和论坛版主 <br>\n也是名自媒体创作博主，Vlogger <br>\n正在研发一款ARTS游戏，希望能火。 <br>\n<a href=\"https://space.bilibili.com/331466888?spm_id_from=333.999.0.0\" target=\"_blank\" rel=\"noopener noreferrer\">https://space.bilibili.com/331466888?spm_id_from=333.999.0.0</a></p>","r":{"minutes":0.6,"words":180},"y":"a","t":"介绍页","i":"info","I":1},["/zh/intro","/zh/intro.md"]],
  ["v-2d0ad528","/zh/",{"y":"h","t":"主页","i":"home","I":1},["/zh/index.html","/zh/README.md"]],
  ["v-c38fab7a","/posts/project/cookdesigner/devnote.html",{"d":"2023-02-03T00:00:00.000Z","l":"February 3, 2023","c":["program"],"g":["red"],"e":"<h1> CookDesigner Development Notes</h1>\n","r":{"minutes":0.04,"words":13},"y":"a","t":"CookDesigner Development Notes","i":"edit","I":1},["/posts/project/cookdesigner/devnote","/posts/project/cookdesigner/devnote.md"]],
  ["v-0a9d4134","/zh/posts/project/cookdesigner/devnote.html",{"d":"2023-02-03T00:00:00.000Z","l":"2023年2月3日","c":["我的项目"],"g":["红"],"e":"<h1> CookDesigner 开发笔记</h1>\n","r":{"minutes":0.06,"words":18},"y":"a","t":"CookDesigner 开发笔记","i":"edit","I":1},["/zh/posts/project/cookdesigner/devnote","/zh/posts/project/cookdesigner/devnote.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":"","I":1},["/404"]],
  ["v-423bc011","/posts/project/cookdesigner/",{"y":"p","t":"Cookdesigner","I":1},["/posts/project/cookdesigner/index.html"]],
  ["v-1ad3662b","/posts/project/",{"y":"p","t":"Project","I":1},["/posts/project/index.html"]],
  ["v-e1e3da16","/posts/",{"y":"p","t":"Posts","I":1},["/posts/index.html"]],
  ["v-19def882","/zh/posts/project/cookdesigner/",{"y":"p","t":"Cookdesigner","I":1},["/zh/posts/project/cookdesigner/index.html"]],
  ["v-0f884a1a","/zh/posts/project/",{"y":"p","t":"Project","I":1},["/zh/posts/project/index.html"]],
  ["v-564155e4","/zh/posts/",{"y":"p","t":"Posts","I":1},["/zh/posts/index.html"]],
  ["v-5bc93818","/category/",{"y":"p","t":"Category","I":1},["/category/index.html"]],
  ["v-744d024e","/tag/",{"y":"p","t":"Tag","I":1},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"y":"p","t":"Articles","I":1},["/article/index.html"]],
  ["v-154dc4c4","/star/",{"y":"p","t":"Star","I":1},["/star/index.html"]],
  ["v-01560935","/timeline/",{"y":"p","t":"Timeline","I":1},["/timeline/index.html"]],
  ["v-25d05243","/category/program/",{"y":"p","t":"program Category","I":1},["/category/program/index.html"]],
  ["v-b306f5e8","/tag/red/",{"y":"p","t":"red Tag","I":1},["/tag/red/index.html"]],
  ["v-54d7ff21","/zh/article/",{"y":"p","t":"文章","I":1},["/zh/article/index.html"]],
  ["v-2c3ee7f5","/zh/star/",{"y":"p","t":"收藏","I":1},["/zh/star/index.html"]],
  ["v-27b02be6","/zh/timeline/",{"y":"p","t":"时间轴","I":1},["/zh/timeline/index.html"]],
  ["v-fbb94a6e","/zh/category/",{"y":"p","t":"分类","I":1},["/zh/category/index.html"]],
  ["v-540234fd","/zh/tag/",{"y":"p","t":"标签","I":1},["/zh/tag/index.html"]],
  ["v-381604b7","/zh/category/%E6%88%91%E7%9A%84%E9%A1%B9%E7%9B%AE/",{"y":"p","t":"我的项目 分类","I":1},["/zh/category/我的项目/","/zh/category/%E6%88%91%E7%9A%84%E9%A1%B9%E7%9B%AE/index.html"]],
  ["v-03d1f283","/zh/tag/%E7%BA%A2/",{"y":"p","t":"红 标签","I":1},["/zh/tag/红/","/zh/tag/%E7%BA%A2/index.html"]],
]
